### ISSUE TITLE
MongoDBreakout - "Sticky Ball"

### ISSUE THREAD

**Issue by Cborek** [thawkin3/201R#10]
@thawkin3 

When colliding with the paddle from the side. The ball will 'stick' to the paddle. Depending on the situation, I have found that the ball will behave in one of two ways: 

- If the paddle is stationary, the ball will glide across the surface of the paddle and move from the paddle straight into the wall. 

- If the paddle is moving in the opposite direction of the ball, the ball will count this as a bounce but will not leave the paddle. The ball will continue to bounce multiple times and eventually will leave the paddle traveling in the same direction as the paddle at an increased speed as the game seems to think the ball has bounced multiple times.

This issue only occurs when the ball is 'skewered' by the top of the paddle. Otherwise, the ball will just clip through the side of the paddle. I'm assuming that collision detection for the paddle only occurs on the top. I'd suggest maybe adding collisions to the side of the paddle to avoid this issue.

Failed Test Case: Ball Bounces off Paddle (MB-4)

**Comment by thawkin3** [comment]
@Cborek Nice. I was able to reproduce this by moving my paddle slightly to the left when the game starts. Then the ball bounces off the right wall, hits the right edge of the paddle, glides across the paddle, and then leaves it from the left side of the paddle and moves upward. You're right that I'm probably just doing the hit detection on the top of the padding and it's getting "skewered" by colliding with the paddle somewhere along its side.

I'll look into it and see what I can do.

**Comment by thawkin3** [comment]
@Cborek Ok this should be fixed now. Can you re-test?
