### ISSUE TITLE
Qrappy Bird - error message on Chrome Version 67.0.3396.99

### ISSUE THREAD

**Issue by abruton** [thawkin3/201R#19]
_Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD_

Although this issue is not in newer versions of Chrome; since people will have to actively be looking for it even when it doesn't show in the console. 
 _"You'll need to go to the url, open up the JS Console, then in the address bar remove the hash, then hit enter to refresh the page, and then you should see the error hopefully."_

**Comment by thawkin3** [comment]
@abruton Thanks! I'll look into this one. Basically it looks like Chrome is starting to enforce some of the same behaviors that mobile devices do. On mobile devices, audio doesn't get played automatically until the user interacts with the page, so you can't play annoying music without them basically clicking on a play button (although really you can trigger it off of any interaction, so technically you can still be annoying and play audio when the user does something that they wouldn't expect to trigger a sound. But I digress.) So it looks like Chrome is enforcing that same rule now, which is neat.

**Comment by thawkin3** [comment]
@abruton This should be fixed now. Could you please re-test? You should be able to see the following behavior on the latest version of Chrome:

If the audio is blocked from autoplaying by Chrome, then you should not see an error message in the browser's JavaScript console. The text on the bottom right of the game should say "Play Theme Song". Clicking on that text should play the music. I'm able to reproduce this in Chrome 67 by going to the url without the hash that Angular adds: http://ec2-54-200-192-157.us-west-2.compute.amazonaws.com/201R/QrappyBird/

If the audio is not blocked by Chrome from autoplaying, then you should be hearing the audio play, and the text on the bottom right of the game should say "Pause Theme Song". Clicking on that text should pause the music. Clicking on the text again should play the music.
