### ISSUE TITLE
Chrome "[Violation]" Issues

### ISSUE THREAD

**Issue by abruton** [thawkin3/201R#20]
For _Qrappy Bird, Connect Four, and Tic Tac Toe_ I'm seeing performance bottlenecks, although I know these could potential not be fixed I figured it would be best to log them anyway, because these potentially affect Qrappy Bird when it comes to a high score.

**Comment by thawkin3** [comment]
@abruton Thanks for logging this. I'm not 100% sure I know what you'e saying though. Do you have examples of what "performance bottlenecks" you're seeing? Or what "Chrome violation issues" you're seeing? Any specific examples, screenshots, error messages, or steps to reproduce would be helpful. Generally, the more info you can provide when logging something, the better. Thanks!

**Comment by thawkin3** [comment]
@abruton I'm going to close this one since I haven't heard back from you and there isn't any actionable info.
